import type { PublicDataset } from "./domain";

export const sanFernandoPublicDatasets: PublicDataset[] = [
  {
    id: "cne-electoral-circuits",
    municipalityId: "municipio-san-fernando",
    name: "Circuitos electorales de San Fernando",
    category: "Límites territoriales",
    publisher: "Cámara Nacional Electoral / Datos Argentina",
    sourceUrl: "https://datos.gob.ar/dataset/justicia-circuitos-electorales",
    license: "CC BY 4.0",
    format: "GeoJSON",
    recordCount: 16,
    version: "2026-07-28",
    updatedAt: "2026-07-28T00:00:00.000Z",
    lastCheckedAt: "2026-07-28T00:00:00.000Z",
    status: "verified",
    validation: "Geometrías válidas, identificadores únicos y pertenencia municipal comprobada.",
    provenance: "Capa oficial conservada separada de observaciones y actividades propias.",
  },
  {
    id: "sf-municipality-boundary",
    municipalityId: "municipio-san-fernando",
    name: "Límite municipal derivado",
    category: "Municipio",
    publisher: "ATIY, derivado de circuitos CNE",
    sourceUrl: "https://datos.gob.ar/dataset/justicia-circuitos-electorales",
    license: "CC BY 4.0",
    format: "GeoJSON",
    recordCount: 1,
    version: "2026-07-28",
    updatedAt: "2026-07-28T00:00:00.000Z",
    lastCheckedAt: "2026-07-28T00:00:00.000Z",
    status: "verified",
    validation: "Disolución determinística de las geometrías electorales documentadas.",
    provenance: "Dato derivado; no reemplaza ni altera la fuente oficial.",
  },
  {
    id: "osm-territorial-areas",
    municipalityId: "municipio-san-fernando",
    name: "Localidades y áreas territoriales",
    category: "Localidades y barrios",
    publisher: "OpenStreetMap contributors",
    sourceUrl: "https://www.openstreetmap.org/copyright",
    license: "ODbL",
    format: "GeoJSON",
    recordCount: 4,
    version: "2026-07-28",
    updatedAt: "2026-07-28T00:00:00.000Z",
    lastCheckedAt: "2026-07-28T00:00:00.000Z",
    status: "verified",
    validation: "Coordenadas y nombres normalizados; sin geometrías inventadas.",
    provenance: "Información pública; se mantiene separada del conocimiento operativo.",
  },
  {
    id: "sf-health-catalog",
    municipalityId: "municipio-san-fernando",
    name: "Catálogo de establecimientos de salud",
    category: "Salud",
    publisher: "Municipalidad de San Fernando",
    sourceUrl: "https://www.sanfernando.gob.ar/",
    license: "Fuente pública institucional",
    format: "JSON",
    recordCount: 1,
    version: "2026-07-28",
    updatedAt: "2026-07-28T00:00:00.000Z",
    lastCheckedAt: "2026-07-28T00:00:00.000Z",
    status: "verified",
    validation: "Solo registros cuya ubicación y denominación fueron verificadas.",
    provenance: "No se completan faltantes con datos sintéticos.",
  },
  {
    id: "sf-pending-catalogs",
    municipalityId: "municipio-san-fernando",
    name: "Catálogos institucionales pendientes",
    category: "Educación, cultura y seguridad",
    publisher: "Fuentes públicas por validar",
    sourceUrl: "https://www.sanfernando.gob.ar/",
    license: "A confirmar por conjunto",
    format: "CSV",
    recordCount: 0,
    version: "sin importar",
    updatedAt: "2026-07-28T00:00:00.000Z",
    lastCheckedAt: "2026-07-28T00:00:00.000Z",
    status: "pending",
    validation: "La arquitectura está lista; no se publican registros sin trazabilidad suficiente.",
    provenance: "Pendiente de revisión humana y aceptación de versión.",
  },
];
